# Generated by Django 3.2 on 2022-03-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_shopingcart_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamount",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_shop",
                to="api.recipe",
                verbose_name="resipe_amount",
            ),
        ),
    ]
