# Generated by Django 3.2 on 2022-02-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220127_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_cart', to='api.recipe', verbose_name='Rcipe'),
        ),
    ]
